### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [hoelzro/p6-algorithm-elo#4]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that these distributions:

- https://github.com/hoelzro/p6-algorithm-elo
- https://github.com/hoelzro/p6-algorithm-lcs
- https://github.com/hoelzro/p6-io-string
- https://github.com/hoelzro/p6-pod-eod
- https://github.com/hoelzro/p6-priorityqueue

will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining these distributions, you can have these distributions moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by hoelzro** [comment]
Thanks for the notification @lizmat ! You can put all of those modules up for adoption.

**Comment by lizmat** [comment]
Thanks for your reply!

I've given you the right to transfer these modules to raku-community-modules.  Once there, someone (probably me) will take care of them to move them to the zef ecosystem.

**Comment by lizmat** [comment]
I've forked Algorithm::Elo, Algorithm::CLS and Pod::EOD, updated them and re-released to the zef ecosystem.  You can archive these now: transfer is no longer needed.

**Comment by hoelzro** [comment]
Thanks @lizmat ! I'll go ahead and archive those, then.
